name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix: ${{ matrix.arch.name }}
      - run: cargo clippy  --all-targets -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo test --all-features
